import { Recipe } from './models/recipe.r';

export const provisionalData: Recipe[] = [
  {
    idMeal: '1',
    strMeal: 'Espaguetis',
    strCategory: 'dessert',
    strArea: 'Spain',
    strInstructions: 'Coges el pan, lo metes en leche y lo fríes',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/0jv5gx1661040802.jpg',
    strIngredient1: 'leche',
    strIngredient2: 'cacao',
    strIngredient3: 'avellanas',
    strIngredient4: 'azúcar',
    strIngredient5: 'huevos',
    strIngredient6: '',
    strIngredient7: '',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strMeasure1: '250ml',
    strMeasure2: '1 sobre',
    strMeasure3: '5',
    strMeasure4: '250ml',
    strMeasure5: '250ml',
    strMeasure6: '2',
    strMeasure7: '',
    strMeasure8: '',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
  },
  {
    idMeal: '2',
    strMeal: 'Sushi',
    strCategory: 'dessert',
    strArea: 'Spain',
    strInstructions: 'Coges el pan, lo metes en leche y lo fríes',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
    strIngredient1: 'leche',
    strIngredient2: 'cacao',
    strIngredient3: 'avellanas',
    strIngredient4: 'azúcar',
    strIngredient5: 'huevos',
    strIngredient6: '',
    strIngredient7: '',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strMeasure1: '250ml',
    strMeasure2: '1 sobre',
    strMeasure3: '5',
    strMeasure4: '250ml',
    strMeasure5: '250ml',
    strMeasure6: '2',
    strMeasure7: '',
    strMeasure8: '',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
  },
];
